### ISSUE TITLE
Add version/build date

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/sacro#122] opened 2023-06-29 15:49 UTC
We currently hardcode the version as 0.1.0 in both sacro-app/package.json ~and pyoxidizer.bzl~ (only package.json matters currently).

We will want process/tooling to bump it. 

We should also find a way to include a build date, in the version or other metadata.

Ideally, we'd make this visible in the UI, possibly via a menu option.

**Comment by lucyb** [comment] 2023-07-03 10:58
The display of the build date part of this ticket has been broken out into https://github.com/opensafely-core/sacro/issues/132

**Comment by madwort** [comment] 2023-07-05 08:42
closing as duplicate of #132

**Closed by madwort** 2023-07-05 08:42 UTC
Labels: sacro
